-- AlterTable
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "orgRoles" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "direction" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "isTechnical" BOOLEAN NOT NULL DEFAULT false;
