name: Deploy Frontend and Backend to Ubuntu Server

on:
    push:
        branches: [master]

jobs:
    deploy-frontend:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "22"

            - name: Install dependencies and build frontend
              working-directory: ./frontend
              run: |
                  npm install
                  npm run build
                  ls -la dist/

            - name: Deploy frontend to server
              uses: appleboy/scp-action@v1
              with:
                  host: ${{ secrets.SERVER_IP }}
                  username: ${{ secrets.SERVER_USER }}
                  key: ${{ secrets.SERVER_SSH_KEY }}
                  port: ${{ secrets.SERVER_SSH_PORT || '22' }}
                  source: "frontend/dist/**"
                  target: "/var/www/alexol.io/html"
                  overwrite: true
                  strip_components: 2

    deploy-backend:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Create .env file from secret
              run: |
                  echo "${{ secrets.ENV_BE }}" > backend/.env

            - name: Deploy backend to server
              uses: appleboy/scp-action@v1
              with:
                  host: ${{ secrets.SERVER_IP }}
                  username: ${{ secrets.SERVER_USER }}
                  key: ${{ secrets.SERVER_SSH_KEY }}
                  port: ${{ secrets.SERVER_SSH_PORT || '22' }}
                  source: "backend/**"
                  target: "/var/www/alexol.io/back"
                  overwrite: true
                  strip_components: 1

            - name: Start backend with Docker Compose
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.SERVER_IP }}
                  username: ${{ secrets.SERVER_USER }}
                  key: ${{ secrets.SERVER_SSH_KEY }}
                  port: ${{ secrets.SERVER_SSH_PORT || '22' }}
                  script: |
                      cd /var/www/alexol.io/back
                      docker-compose down
                      docker-compose up -d --build
                      docker-compose ps
